/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import gsap from "gsap";
import {useGSAP} from "@gsap/react";

const ReactLogo = (props) => {
  const { nodes, materials } = useGLTF('/models/banana-v2-transformed.glb')
  
  return (
    <Float floatIntensity={1} >
        <group position = {[8,8,0]} scale={0.5} {...props} dispose={null}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.banana_high.geometry}
            material={materials.skin}
            rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.banana_mid.geometry}
                material={materials.skin}
                rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.banana_low.geometry}
                material={materials.skin}
                rotation={[-Math.PI / 2, 0, 0]}
            />
        </group>
      
    </Float>
  )
}

useGLTF.preload('/models/banana-v2-transformed.glb')

export default ReactLogo
